Migrate to redux-persist v5.
infinitered/ignite-redux-persist pull request #5
Opened 2017-12-03 18:55 UTC by Amurmurmur

Bump version to 0.1.0.
Breaking changes.

2017-12-05 18:56 UTC, ryanlntn requested changes
@Amurmurmur Thanks for this! There are a couple issues I'm seeing when igniting a new app. Please see my comments.

2017-12-05 18:56 UTC, ryanlntn commented on plugin.js
> +    let finalReducers = reducers
It looks like there are some whitespace issues here. These need to be unindented by two spaces to be formatted properly. Right now it looks like this:

![image](https://user-images.githubusercontent.com/1944151/33624482-64c406dc-d9a9-11e7-8fd8-77258d33fbad.png)

A newline at the end would be nice too. 😄

2017-12-05 18:56 UTC, ryanlntn commented on plugin.js
> +  ignite.patchInFile(`${APP_PATH}/App/Containers/RootContainer.js`, {
It looks like this should be in `${APP_PATH}/App/Redux/index.js` now.

2017-12-05 18:56 UTC, ryanlntn commented on plugin.js
> +    let finalReducers = reducers
You'll want to update whitespace here as well.

2017-12-05 18:56 UTC, ryanlntn commented on templates/Rehydration.js
> -  const config = ReduxPersist.storeConfig
Can you explain this change? Do we not need to apply the config here now?

2017-12-05 18:56 UTC, ryanlntn commented on plugin.js
> +  ignite.patchInFile(`${APP_PATH}/App/Containers/RootContainer.js`, {
And this will need to be updated to `${APP_PATH}/App/Redux/index.js` too.

2017-12-05 19:37 UTC, ryanlntn commented on templates/Rehydration.js
> -  const config = ReduxPersist.storeConfig
Nevermind. I just checked out the migration guide https://github.com/rt2zz/redux-persist#migration-from-v4-to-v5

2017-12-06 13:24 UTC, Amurmurmur commented
@ryanlntn Please check the changes. Thank you very much for pointing them out 👍

2017-12-06 17:09 UTC, ryanlntn approved these changes
Awesome! Thanks @Amurmurmur

2017-12-06 17:09 UTC, merged